env:
  es2021: true
extends:
  - 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    jsx: false
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - never
