stellaris:
  executable: C:/SteamHome/steamapps/common/Stellaris/Stellaris.exe
  arguments: []
  root:
  launcher:
    executable: AppData/Local/Programs/Paradox Interactive/launcher/launcher-v2.2021.6/Paradox Launcher.exe
    root:
  documents:
    root: Documents/Paradox Interactive/Stellaris
    db: launcher-v2.sqlite
    logs: logs
    mods: mods
    crashes: crashes
  imageMagickHome: C:/ImageMagick710Q16HDRI-x64
  output:
